### ISSUE TITLE
Please add outputs.has-new-commits

### ISSUE THREAD

**Issue by cognifloyd** [aormsby/Fork-Sync-With-Upstream-action#3]
I would like to use `if: steps.sync.outputs.has-new-commits` so that subsequent steps only run when there are new commits.

modifying the example from the readme:

```yaml
jobs:
  repo-sync:
    steps:
    - name: Checkout master
      ...
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v1
      with:
        upstream_repository: panr/hugo-theme-hello-friend
        upstream_branch: master
        target_branch: master                       # optional
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that requir authentication
        
    - name: Timestamp
      if: steps.sync.outputs.has-new-commits
      run: date
```
