### ISSUE TITLE
Merge Conflicts 

### ISSUE THREAD

**Issue by RyanGaudion** [aormsby/Fork-Sync-With-Upstream-action#59]
Hi,

I am receiving merge conflicts during my sync. How can I force the sync to go through overwriting target with source?

this is my action step:

```
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: gh-pages
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        target_branch_push_args: '--force'
        upstream_sync_branch: gh-pages
        upstream_sync_repo: MyOrg/MyRepo
        upstream_pull_args: '--allow-unrelated-histories'
        upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}

        test_mode: false
```

and these are my errors:

```
* branch            gh-pages   -> FETCH_HEAD
Auto-merging 404.html
CONFLICT (add/add): Merge conflict in 404.html
Auto-merging design/index.html
CONFLICT (add/add): Merge conflict in design/index.html
Auto-merging extra/index.html
CONFLICT (add/add): Merge conflict in extra/index.html
Auto-merging index.html
CONFLICT (add/add): Merge conflict in index.html
Auto-merging onboarding/index.html
CONFLICT (add/add): Merge conflict in onboarding/index.html
Auto-merging sitemap.xml
CONFLICT (add/add): Merge conflict in sitemap.xml
warning: Cannot merge binary files: sitema...
Auto-merging sitemap.xml.gz
CONFLICT (add/add): Merge conflict in sitemap.xml.gz
Auto-merging storybook/project.json
CONFLICT (add/add): Merge conflict in storybook/project.json
Auto-merging strategy/index.html
CONFLICT (add/add): Merge conflict in strategy/index.html
Automatic merge failed; fix conflicts and then commit the result.
ERROR:  exit 1
```
