### ISSUE TITLE
shallow update not allowed

### ISSUE THREAD

**Issue by aidenpearce001** [aormsby/Fork-Sync-With-Upstream-action#66]
It worked few days ago but today i got this error and still not find solution yet :
! [remote rejected]     main -> main (shallow update not allowed)

**Comment by aormsby** [comment]
Please provide more info, or I can't help

**Comment by GGeorggg** [comment]
Hi, 

same for me too: 
it broke somewhere between 2023-01-27T17:42:29.8455646Z and 2023-02-03T10:26:18.9201843Z 

The only difference i can see is the image:

https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230122.1 (OK)
https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230129.2 (BROKE)

when ```Pushing synced data to target branch.```  is called,  i do get:

```
 ! [remote rejected]         MOODLE_401_STABLE -> MOODLE_401_STABLE (shallow update not allowed)
```

i already switched v3 to run an unshallow checkout: 

``` 
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref: MOODLE_401_STABLE
        persist-credentials: false
        fetch-depth: 0
``` 
however that did not fix the issue 

the new docker image could have changed the git Version, as there was a change commited on 11 Jan 2023 15:12:27 -0300

http://changelogs.ubuntu.com/changelogs/pool/main/g/git/git_2.34.1-1ubuntu1.6/changelog

regards
Georg
