### ISSUE TITLE
[Output variable] List of specific file changes

### ISSUE THREAD

**Issue by LangLangBart** [aormsby/Fork-Sync-With-Upstream-action#68]
#### description
- the [README](https://github.com/aormsby/Fork-Sync-With-Upstream-action#output-variables) states to open a new issue for more `Output Variables`
- could you provide a variable to see what kind of files have been changed

#### use case
- I would like to check if the list of new commits includes '.cpp' files

```yml
# example with a made up variable called 'file_changes_include'
    - name: New commits found and it includes '.cpp' changes
	  if: |
		(steps.sync.outputs.has_new_commits == 'true' &&
		steps.sync.outputs.file_changes_include == '*cpp*')
      run: |
	    echo "New commits were found to sync."
		make
```

---

PS: The `action` works very well, a good job of you to make it available to the public.

**Comment by LangLangBart** [comment]
- the `git_log_format_args` with `--pretty=format:"" --patch --name-only` shows me the files of interest in the logs, is there any way to access them in later steps so I can read out the information I want?

```yml
    steps:
      - uses: actions/checkout@v3
      - uses: aormsby/Fork-Sync-With-Upstream-action@main
        id: sync
        with:
          # rebase the local branch on top of the remote changes
          git_config_pull_rebase: true
          target_sync_branch: testing
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # list
          git_log_format_args: --pretty=format:"" --patch --name-only
          # force push, because of the rebase
          target_branch_push_args: --force
          upstream_sync_branch: master
          upstream_sync_repo: 0ad/0ad
          upstream_pull_args: --ff --no-edit
          test_mode: false
```

<img src="https://github.com/aormsby/Fork-Sync-With-Upstream-action/assets/92653266/3bf1509e-bba4-4549-b732-b7807b95f4eb" width="800">
