### ISSUE TITLE
Fail to sync when target branch has Branch protection rule

### ISSUE THREAD

**Issue by maze88** [aormsby/Fork-Sync-With-Upstream-action#76]
## Overview
With a `target_sync_branch` that has a _Branch protection rule_ configured and with `target_branch_push_args: --force`, I receive the following error:
```
Pushing synced data to target branch.
remote: error: GH006: Protected branch update failed for refs/heads/my-target-branch.        
remote: error: Changes must be made through a pull request.
```

## Expected behavior
For the sync to occur successfully, even though the target branch is protected.

## Additional details
- The _Branch protection rule_ is configured to:
  - _Require a pull request before merging_ (with  _Require approvals_=1).
  - _Allow force pushes_ (by _Everyone_).
-  Here is the step from my workflow (with some substitutions for clarity):
   ```yaml
   steps:
   - name: Checkout target repo
     uses: actions/checkout@v3
     with:
       ref: ${{ matrix.branch }}  # master & our release branch
   - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
     with:
       git_config_user: my-ci-cd
       git_config_email: my-ci-cd@our-org.com
       upstream_sync_repo: the-upstream-owner/${{ github.event.repository.name }}
       upstream_sync_branch: master
       target_repo_token: ${{ secrets.GITHUB_TOKEN }}
       target_sync_branch: ${{ matrix.branch }}
       target_branch_push_args: --force
   ```

## Conclusion
There is the possibility that this is user error - that I'm missing some setting or input in the action or branch rule settings - if so then I'd be very happy for some guidance...!
Otherwise, a feature to support such a case may be desired by more users...
