### ISSUE TITLE
Test fails but is reported as passing

### ISSUE THREAD

**Issue by clalexander** [aormsby/Fork-Sync-With-Upstream-action#78]
I'm trying to figure out why I can't sync with my private repository (reviewing #16), and I came across an issue with the test case that checks for the existence of the upstream repository (`test_upstream_repo_exists`). The test fails (in my case because I'm having issues accessing the upstream repo) but it writes out `PASSED`.

## Action Test Output

```
Run aormsby/Fork-Sync-With-Upstream-action@v3.4.1
/usr/bin/sh /home/runner/work/_actions/aormsby/Fork-Sync-With-Upstream-action/v3.4.1/entry/config_and_run.sh
Running TESTS...

TEST
[Verify Target Sync Branch] -> tests 'target_sync_branch' input
PASSED

TEST
[Verify Upstream Sync Repo Exists] -> tests 'upstream_sync_repo' input
remote: Repository not found.
fatal: repository 'https://github.com/<org>/<repo>.git/' not found
PASSED << HERE is the issue

TEST
[Verify Upstream Sync Branch Exists] -> tests 'upstream_sync_branch' input
remote: Repository not found.
fatal: repository 'https://github.com/<org>/<repo>.git/' not found
FAILED - no branch 'main' found on remote repo

TEST
[Upstream Repo Access] -> Try to clone private repo with access token / git clone should succeed
PASSED
(Clone directory cleanup successful.)

TEST
[Config User Name] -> user.name should equal 'GH Action - Upstream Sync'
PASSED

TEST
[Config User Email] -> user.email should equal 'action@github.com'
PASSED

TEST
[Config Pull Settings] -> pull.rebase should equal 'false'
PASSED
(All git configs set back to original user values.)

Tests Complete
```

## My Action

```
name: Sync With Upstream


on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:
    inputs:
      sync_test_mode: # Adds a boolean option that appears during manual workflow run for easy test mode config
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false


jobs:
  sync_with_upstream:
    name: Sync With Upstream
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.sync.outputs.has_new_commits }}
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
        
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        target_branch_push_args: --tags
        upstream_sync_branch: main
        upstream_sync_repo: ${{ vars.UPSTREAM_REPO }}
        upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_ACCESS_TOKEN }}
        upstream_pull_args: --tags

        # Set test_mode true during manual dispatch to run tests instead of the true action!!
        test_mode: ${{ inputs.sync_test_mode }}
```

## Analysis

In reviewing the test cases, I think the issue is that there is an incorrect check on the result of the test. At [test/verify_branches.sh:21](https://github.com/aormsby/Fork-Sync-With-Upstream-action/blob/1090e365224fc834e7e1de521c417ded2d6fcb53/test/verify_branches.sh#L21), the if statement checks for a non-zero length variable `-n` for failure instead of a zero-length variable `-z`, as it does in the other two checks in the same file (line 8 and 35).

I can create a PR if you would like.
